name: cestimator CI

on:
  push:
    branches:
      - development
      - master
  pull_request:
    branches:
      - development
      - master

jobs:
  cppcheck:
    runs-on: ubuntu-latest
    name: Check for missed errors

    env:
      BUILD_TYPE: Debug

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up cppcheck
        run: sudo apt install -y cppcheck

      - name: Verify
        run: cppcheck src/**/*.cpp --force

  cpp_style_check:
    runs-on: ubuntu-latest
    name: Conform all to consistent style
    steps:
    - name: Checkout this commit
      uses: actions/checkout@v2
    - name: Run style checks
      uses: dalpapa/actions-uncrustify@v1
      with: 
        configPath: 'ucfy.cfg'

  build:
    runs-on: ubuntu-latest

    env:
      BUILD_TYPE: Debug

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GCC-13
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update
          sudo apt install gcc-13 g++-13 -y
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-13 60
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-13 60
          sudo update-alternatives --set gcc /usr/bin/gcc-13
          sudo update-alternatives --set g++ /usr/bin/g++-13

      - name: Install dependencies
        run: sudo apt install -y libeigen3-dev libmgl-dev

      - name: Configure
        run: |
          autoreconf -ifv
          ./configure --with-visualization

      - name: Build
        run: make

      - name: Build examples
        run: make examples
  