language: cpp
dist: bionic
compiler: gcc

install:
  - sudo apt update
  - sudo apt install -y libeigen3-dev libmgl-dev


branches:
  only:
    - development
    - master

jobs:
  include:
    - stage: build
      script:
        - ./configure --with-visualization
        - make
        - make examples