language: cpp
dist: bionic
compiler: gcc

install:
  - sudo apt update
  - sudo apt install libeigen3-dev libmgl-dev

script:
  - ./configure --with-visualization
  - make
  - make examples

on: 
  push
  pull_request:
    branches:
      - development
      - master

jobs:
  install
  script